import argparse
import csv
import json
import os
import subprocess
import sys
import time
from pathlib import Path


PHASE6_FIELDS = [
    "task",
    "task_source",
    "benchmark_scope",
    "method",
    "attention_backend",
    "N",
    "B",
    "d",
    "K_eff",
    "params",
    "seed",
    "valid_metric",
    "test_metric",
    "final_valid_loss",
    "final_valid_accuracy",
    "memory_gb",
    "tokens_per_sec",
    "profile_protocol",
    "artifact_dir",
    "command_path",
    "data_version",
    "notes",
]


def write_command(path: Path, argv: list[str], env: dict[str, str]) -> None:
    path.write_text(
        " ".join([f"{key}={value}" for key, value in sorted(env.items()) if key.startswith("CUDA_VISIBLE_DEVICES")])
        + "\n"
        + " ".join(argv)
        + "\n",
        encoding="utf-8",
    )


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def count_params_from_config(config: dict) -> str:
    model = config.get("model", {})
    return json.dumps(model, sort_keys=True)


def synthetic_row(summary: dict, result: dict, artifact_dir: Path, command_path: Path, data_version: str) -> dict:
    mask = result.get("mask", {})
    return {
        "task": result["task"],
        "task_source": "synthetic",
        "benchmark_scope": "synthetic_only",
        "method": result["method"],
        "attention_backend": result["attention_backend"],
        "N": result["seq_len"],
        "B": result["block_size"],
        "d": result["degree"],
        "K_eff": mask.get("effective_k_mean"),
        "params": count_params_from_config(summary.get("config", {})),
        "seed": summary.get("config", {}).get("seed"),
        "valid_metric": result.get("final_valid_accuracy"),
        "test_metric": "",
        "final_valid_loss": result.get("final_valid_loss"),
        "final_valid_accuracy": result.get("final_valid_accuracy"),
        "memory_gb": result.get("peak_reserved_gb"),
        "tokens_per_sec": result.get("tokens_per_sec"),
        "profile_protocol": "training_loop_single_run",
        "artifact_dir": str(artifact_dir),
        "command_path": str(command_path),
        "data_version": data_version,
        "notes": "Generated by phase6_runner; synthetic result is not an official LRA claim.",
    }


def listops_or_imdb_row(task: str, result: dict, artifact_dir: Path, command_path: Path, data_version: str) -> dict:
    scope = "official_lra_candidate" if task == "listops" else "lra_text_imdb"
    return {
        "task": task,
        "task_source": "official_lra" if task == "listops" else "imdb_text",
        "benchmark_scope": scope,
        "method": "dense",
        "attention_backend": "bert_dense",
        "N": result.get("max_length"),
        "B": "",
        "d": "",
        "K_eff": result.get("max_length"),
        "params": json.dumps(
            {
                "hidden_size": result.get("hidden_size"),
                "layers": result.get("layers"),
                "heads": result.get("heads"),
            },
            sort_keys=True,
        ),
        "seed": result.get("seed"),
        "valid_metric": result.get("eval_accuracy"),
        "test_metric": "",
        "final_valid_loss": result.get("eval_loss"),
        "final_valid_accuracy": result.get("eval_accuracy"),
        "memory_gb": result.get("peak_reserved_gb"),
        "tokens_per_sec": result.get("tokens_per_sec"),
        "profile_protocol": "base_smoke_training_loop",
        "artifact_dir": str(artifact_dir),
        "command_path": str(command_path),
        "data_version": data_version,
        "notes": "Dense base smoke; sparse base integration is gated on official data readiness.",
    }


def run_command(argv: list[str], artifact_dir: Path, env: dict[str, str]) -> subprocess.CompletedProcess:
    artifact_dir.mkdir(parents=True, exist_ok=True)
    command_path = artifact_dir / "command.sh"
    write_command(command_path, argv, env)
    started = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    completed = subprocess.run(argv, cwd=Path.cwd(), env={**os.environ, **env}, text=True)
    ended = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    (artifact_dir / "run_meta.json").write_text(
        json.dumps({"started": started, "ended": ended, "returncode": completed.returncode}, indent=2) + "\n",
        encoding="utf-8",
    )
    return completed


def write_table(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.DictWriter(fp, fieldnames=PHASE6_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", choices=["copy_first", "associative_recall", "listops", "imdb"], default="copy_first")
    parser.add_argument("--repo-dir", type=Path, default=Path("code/lra-benchmarks"))
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/phase6_runner"))
    parser.add_argument("--methods", default="dense,local,random,zigzag")
    parser.add_argument("--attention-backend", default="auto_split")
    parser.add_argument("--seq-len", type=int, default=1024)
    parser.add_argument("--block-size", type=int, default=16)
    parser.add_argument("--degree", type=int, default=2)
    parser.add_argument("--steps", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--eval-batches", type=int, default=5)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--data-version", default="unverified")
    parser.add_argument("--cuda-visible-devices", default="")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    env = {}
    if args.cuda_visible_devices != "":
        env["CUDA_VISIBLE_DEVICES"] = args.cuda_visible_devices

    artifact_dir = args.output_dir / f"{args.task}_seed{args.seed}"
    rows: list[dict] = []
    if args.task in {"copy_first", "associative_recall"}:
        argv = [
            sys.executable,
            "scripts/synthetic_mvp.py",
            "--task",
            args.task,
            "--methods",
            args.methods,
            "--attention-backend",
            args.attention_backend,
            "--seq-len",
            str(args.seq_len),
            "--block-size",
            str(args.block_size),
            "--degree",
            str(args.degree),
            "--steps",
            str(args.steps),
            "--batch-size",
            str(args.batch_size),
            "--eval-batches",
            str(args.eval_batches),
            "--seed",
            str(args.seed),
            "--output-dir",
            str(artifact_dir),
        ]
        command_path = artifact_dir / "command.sh"
        if args.dry_run:
            artifact_dir.mkdir(parents=True, exist_ok=True)
            write_command(command_path, argv, env)
        else:
            completed = run_command(argv, artifact_dir, env)
            if completed.returncode != 0:
                raise SystemExit(completed.returncode)
            summary = read_json(artifact_dir / "summary.json")
            rows = [
                synthetic_row(summary, result, artifact_dir, command_path, args.data_version)
                for result in summary["results"]
            ]
    else:
        script = "scripts/listops_base_smoke.py"
        argv = [
            sys.executable,
            script,
            "--repo-dir",
            str(args.repo_dir),
            "--steps",
            str(args.steps),
            "--batch-size",
            str(args.batch_size),
            "--eval-batches",
            str(args.eval_batches),
            "--seed",
            str(args.seed),
            "--output-json",
            str(artifact_dir / "summary.json"),
            "--metrics-jsonl",
            str(artifact_dir / "metrics.jsonl"),
        ]
        if args.task == "imdb":
            argv.extend(["--task", "imdb"])
        command_path = artifact_dir / "command.sh"
        if args.dry_run:
            artifact_dir.mkdir(parents=True, exist_ok=True)
            write_command(command_path, argv, env)
        else:
            completed = run_command(argv, artifact_dir, env)
            if completed.returncode != 0:
                raise SystemExit(completed.returncode)
            result = read_json(artifact_dir / "summary.json")
            rows = [listops_or_imdb_row(args.task, result, artifact_dir, command_path, args.data_version)]

    if rows:
        write_table(args.output_dir / "phase6_results.csv", rows)
        (args.output_dir / "phase6_results.jsonl").write_text(
            "".join(json.dumps(row) + "\n" for row in rows),
            encoding="utf-8",
        )
    print(json.dumps({"status": "ok", "rows": rows, "artifact_dir": str(artifact_dir)}, indent=2), flush=True)


if __name__ == "__main__":
    main()
